RegisterCommand("help", function()
    local Veh = GetVehiclePedIsIn(GetPlayerPed(-1), false)
    local Plate = GetVehicleNumberPlateText(Veh)
    local EHealth = GetVehicleEngineHealth(Veh)
    local Fuel = GetVehicleFuelLevel(Veh)
    local body1 = GetVehicleBodyHealth(Veh)
    local body2 = GetVehicleBodyHealth_2(Veh)
    local Name1 = GetEntityModel(Veh)
    local Name2 = GetDisplayNameFromVehicleModel(Name1)
    local Colours = GetVehicleColours(Veh)
    local ColourCombination = GetVehicleColourCombination(Veh)
    local ModColor_1 = GetVehicleModColor_1(Veh)
    local ModColor_2 = GetVehicleModColor_2(Veh)
    if Veh == 0 then
        msg("You are not in a vehicle, variable Veh result: ".. Veh)
    else
    msg("Your vehicle ID: ".. Veh)
    msg("Your vehicle Plate: ".. Plate) 
    msg("Your vehicle Engine Health: ".. EHealth)
    msg("Your vehicle Fuel Level: ".. Fuel)
    msg("Your vehicle Body damage: ".. body1 .." and ".. body2)
    msg("Your vehicle model name: ".. Name2)
    msg("Your vehicle Colours : ".. Colours .. " / ColourCombination : " .. ColourCombination .. " / ModColor_1 : " .. ModColor_1 .. " / ModColor_2 : " .. ModColor_2)
    end
end,false)

RegisterCommand("clonecar", function()
    local Veh = GetVehiclePedIsIn(GetPlayerPed(-1), true)
    local Plate = GetVehicleNumberPlateText(Veh)
    local EHealth = GetVehicleEngineHealth(Veh)
    local Fuel = GetVehicleFuelLevel(Veh)
    local body1 = GetVehicleBodyHealth(Veh)
    local body2 = GetVehicleBodyHealth_2(Veh)
    local Name1 = GetEntityModel(Veh)
    local Name2 = GetDisplayNameFromVehicleModel(Name1)
    local Colours = GetVehicleColours(Veh)
    local ColourCombination = GetVehicleColourCombination(Veh)
    local ModColor_1 = GetVehicleModColor_1(Veh)
    local ModColor_2 = GetVehicleModColor_2(Veh)
    --local CustomPrimaryColour = GetVehicleCustomPrimaryColour(Veh)
    --local CustomSecondaryColour = GetVehicleCustomSecondaryColour(Veh)
    local DashboardColor = GetVehicleDashboardColor(Veh)
    local DirtLevel = GetVehicleDirtLevel(Veh)
    local InteriorColor = GetVehicleInteriorColor(Veh)
    local Mod1 = GetVehicleMod(Veh, 1)
    local ModKit = GetVehicleModKit(Veh)
    local NeonLightsColour = GetVehicleNeonLightsColour(Veh)
    local NumberPlateTextIndex = SetVehicleNumberPlateTextIndex(Veh)
    local RoofLivery = GetVehicleRoofLivery(Veh)
    local TyreSmokeColor = GetVehicleTyreSmokeColor(Veh)
    local WheelType = GetVehicleWheelType(Veh)
    local WindowTint = GetVehicleWindowTint(Veh)
    local XenonLightsColor = GetVehicleXenonLightsColor(Veh)
    local x, y, z = table.unpack(GetEntityCoords(Veh, false))
    local ClonedVeh = CreateVehicle(Name2, x + 7, y, z + 1, GetEntityHeading(Veh), true, false)
    SetVehicleModColor_1(ClonedVeh, ModColor_1)
    SetVehicleModColor_2(ClonedVeh, ModColor_2)
    SetVehicleColourCombination(ClonedVeh, ColourCombination)
    SetVehicleColours(clonedVeh, Colours)
    SetVehicleNumberPlateText(ClonedVeh, Plate)
    SetVehicleEngineHealth(ClonedVeh, body1)
    SetVehicleFuelLevel(ClonedVeh, Fuel)
    SetVehicleBodyHealth(ClonedVeh, body1)
    SetEntityAsNoLongerNeeded(Veh)
    SetEntityAsMissionEntity(ClonedVeh)
    --SetVehicleCustomPrimaryColour(ClonedVeh,CustomPrimaryColour)
    --SetVehicleCustomSecondaryColour(ClonedVeh,CustomSecondaryColour)
    SetVehicleDashboardColor(ClonedVeh,DashboardColor)
    SetVehicleDirtLevel(ClonedVeh,DirtLevel)
    SetVehicleInteriorColor(ClonedVeh,InteriorColor)
    SetVehicleMod(ClonedVeh,Mod1)
    SetVehicleModKit(ClonedVeh,ModKit)
    SetVehicleNeonLightsColour(ClonedVeh,NeonLightsColour)
    SetVehicleNumberPlateTextIndex(ClonedVeh,NumberPlateTextIndex)
    SetVehicleRoofLivery(ClonedVeh,RoofLivery)
    SetVehicleTyreSmokeColor(ClonedVeh,TyreSmokeColor)
    SetVehicleWheelType(ClonedVeh,WheelType)
    SetVehicleWindowTint(ClonedVeh,WindowTint)
    SetVehicleXenonLightsColor(ClonedVeh,XenonLightsColor)
    TriggerEvent("chatMessage", "[Server]", {255,0,0}, "Car: ".. Name2 .. " with plates: ".. Plate.. " has been cloned.")
end)

--Function can be set in the botton
function msg(text)
        TriggerEvent("chatMessage", "[Server]", {255,0,0}, text)
end
